name: CS2PR
on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test Project Symlinks
        uses: donatj/annotate-pull-request-from-checkstyle@6046f261c89b5a98a12feae2c3c4369d6adcc2ba
        with:
          files: out.chk
