name: CS2PR
on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test Project Symlinks
        uses: donatj/annotate-pull-request-from-checkstyle@02d1373a9113f624dff987caf783bef6c7c3f77b
        with:
          files: out.chk
