name: CS2PR
on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: donatj/annotate-pull-request-from-checkstyle-action@f3b1d4380b9987171c4f0ab94fcbf13306a823df
        with:
          files: out.chk
