name: CS2PR
on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: staabm/annotate-pull-request-from-checkstyle-action@v1
        with:
          files: out.chk
