name: CS2PR
on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test Project Symlinks
        uses: donatj/annotate-pull-request-from-checkstyle@22516bbdc56e4f50189ac7a7ef5e0f6a5d0220cf
        with:
          files: out.chk
